include: package:lints/recommended.yaml

linter:
  rules:
    prefer_single_quotes: true
    omit_local_variable_types: true

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
